M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-03-24T20:26:18+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-24T20:26:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X148.75Y-49.44
X158.75Y-116.52
X178.9Y-102.7
T2
X151.25Y-39.35
T3
X109.06Y-65.27
X126.2Y-80.4
M30
